os:
  - linux
  - osx
language: node_js
node_js:
- '7'
branches:
  only:
  - master
install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
before_script:
- npm install -g @angular/cli
- npm install -g electron-builder
- npm install -g copy
- npm install
script:
- ng build --prod --aot
- npm run release
cache:
  directories:
  - node_modules
