language: node_js
node_js:
- '7'
branches:
  only:
  - master
addons:
  apt:
    packages:
    - xvfb
    - tree
before_install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      git clone "https://github.com/$TRAVIS_REPO_SLUG.git" "$TRAVIS_REPO_SLUG";
      cd "$TRAVIS_REPO_SLUG";
      git checkout -qf "$TRAVIS_COMMIT";
    fi
install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
before_script:
- npm install -g @angular/cli
- npm install -g electron-builder
- npm install
script:
- ng build --prod
- npm run dist
- tree dist/
cache:
  directories:
  - node_modules
before_deploy:
  - git config --global user.name "jiep" # Replace!
  - git config --global user.email "jiep12345@hotmail.com" # Replace!
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - git checkout master
  - npm run automatic-release # Here happens the magic
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: LVp9R/mU3HM7ER0CrNvbUb3+Rw2mJrHbHbjPSJsJ8qgdFnvmujC/OipRyeSUdGfNH3LWoFTRlJDVDHAPLahro++ssXbyVfmESRYbZvRrBA1v3sTDKIFJursFkt7ftOYHHdzL/T1iCRibZO9jRTK0ft8TYkWt9UrRz9Sw0g2whEe57koFci27mRqhHHLuI69jMmtQWeJn8fCisU9cS7PKZ68Hb0fJkSyZ5DKHcSGkIOnoF8+n160ojVDIdgBV3r3q8XfpG7iWnas/MZTwl2OvSpA+J7eBCc0EtuATGs7X/wMJjz85Wp4zqsIGGdc530DKmLzVIybPhsE4FhpSg+IBSdxU8VNgiKhf4qfKwPU1frDWnWW1h+URNWGcr6/DZ0DlhM0ZtdJCC0xOGpE+fQ6kJsYYRBN78vEciB9y9nh6xtdyI0GJyEj9OjTstUq7Jex7ymDqXCzbXARFAuNukmgKXz98cmHezA2wij91DDH5bl/8Xn19KBD7aid9d698rImd1pHwzf+vNgRo4t44wXpp+mLDT4d+aB0ysmss5BNP8Lj802acwsZVAiDWTPpDmyQ68cTKgQF7uz2tl2QVAjUL8MDZBiC4WzxttY6K7hcfTKMYGZRlx1VIdH77QhMhY/nmfAkVY5QhUPP4MOU+fqwHFHek+gxOZMqRThtf4i90GDs=
  file_glob: true
  file: dist/*.deb
  on:
    tags: true
    all_branches: false
    repo: jiep/angular2-electron-ci
