language: node_js
node_js:
  - "7"
branches:
  only:
    - master
addons:
  apt:
    packages:
      - xvfb
      - tree
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
before_script:
  - npm install -g @angular/cli
  - npm install -g electron-builder
  - npm install

script:
  - ng build --prod
  - npm run dist
  - tree dist/
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/jiep/angular2-electron-cli --tags
  - ls -R
deploy:
  skip_cleanup: true
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - "dist/*.deb"
  on:
    tags: false
    all_branches: false
