language: node_js
node_js:
  - "8"
branches:
  only:
    - master
addons:
  apt:
    packages:
      - xvfb
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
before_script:
  - npm install -g @angular/cli
  - npm install

script:
  - ng build --prod
