os:
  - linux
  - osx
language: node_js
node_js:
- '7'
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
- npm install -g electron-builder
- npm install -g copy
- npm install
script:
- npm run build
- copy main.js package-2.json app/
- mv app/package-2.json app/package.json
- ls -la app/
- npm run release


cache:
  directories:
  - node_modules
