os:
  - linux
  - osx
language: node_js
node_js:
- '7'
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
- npm install -g electron-builder
- npm install -g copy
- npm install
script:
- npm run build
- copy main.js dist/
- ls -la dist/
- npm run release


cache:
  directories:
  - node_modules
