version: 0.1.{build}

platform:
  - x64

cache:
  - node_modules

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 7 x64
  - git reset --hard HEAD
  - npm install electron-builder
  - npm install electron-packager
  - npm install -g @angular/cli
  - npm install -g copy
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run build
  - cp electron/main.js electron/package.json dist/
  - npm run release

test: off
